[workspace]
members = [
    "crates/devvani-lexer",
    "crates/devvani-parser", 
    "crates/devvani-ast",
    "crates/devvani-number",
    "crates/devvani-codegen",
    "crates/devvani-compiler",
    "crates/devvani-cli",
    "crates/devvani-typesystem",
    "crates/devvani-llvm",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["gauravverma-creator"]
description = "A Sanskrit-grammar-based programming language"
license = "MIT"
repository = "https://github.com/gauravverma-creator/Devvani-private"
