[package]
name = "devvani-llvm"
version = "0.1.0"
edition = "2021"

[dependencies]
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm14-0"] }
llvm-sys = { version = "140.1", features = ["force-dynamic"] }
devvani-ast = { path = "../devvani-ast" }
devvani-typesystem = { path = "../devvani-typesystem" }
thiserror = "1.0"
